### ISSUE TITLE
Pre-build and publish binaries as release

### ISSUE THREAD

**Issue by kmturley** [surge-synthesizer/clap-info#11]
**Problem**
As a developer I want to run `clap-info` on a CLAP plugin to extract metadata. Ideally during an automated pipeline or script.
However due to the current setup, every pipeline/script execution has to run the steps:
```
git clone https://github.com/surge-synthesizer/clap-info
cd clap-info
git submodule update --init --recursive
cmake -Bbuild
cmake --build build
```
This requires downloading the git repo and git submodules dependencies (16MB), ensuring the correct `cmake` is installed, running `cmake` and then locating the built binary, which could be in different places per platform:
```
./build/clap-info
./build/clap-info
./build/Release/clap-info.exe
```

**Solution**
Pre-build the binaries once, and publish versions as GitHub releases e.g.:
* clap-info-linux.zip (289 KB)
* clap-info-mac.zip (377 KB)
* clap-info-win.zip (158 KB)

Users can then simply download the binary they need:
```
curl https://github.com/surge-synthesizer/clap-info/releases/download/v1.0.0/clap-info-linux.zip
unzip clap-info-linux.zip
./clap-info-linux/clap-info "/path/to/Surge XT.clap"
```

Ideally these would also be published to system package registries to enable an even faster installation:
```
apt install clap-info
brew install clap-info
choco install clap-info
```

**Comment by kmturley** [comment]
I have made an example release, built automatically with GitHub Actions:
https://github.com/kmturley/clap-info/releases

Will open a PR

**Comment by baconpaul** [comment]
Thank you

I set up azure pipelines before my vaca but didn’t get to the release section. I’m traveling now but  I will review this before this weekend and almost definitely merge it (we plan to move clap info to free audio when I’m back in a week anyway and that is actions only). Very much appreciated!
